# -*- coding: utf-8 -*-
"""EDA_Titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYHalvANnwycVqvX5r9x0B88ZPhkrNBr
"""



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load sample dataset
df = sns.load_dataset("titanic")

# 1. Explore the data structure
print("Dataset Info:")
print(df.info())
print("\nSummary Statistics:")
print(df.describe(include='all'))

# 2. Identify missing values
print("\nMissing Values:")
print(df.isnull().sum())

# 3. Explore categorical features
print("\nUnique Values in Categorical Columns:")
for col in df.select_dtypes(include='object').columns:
    print(f"{col}: {df[col].unique()}")

# 4. Visualize distributions and relationships
sns.countplot(x='sex', data=df)
plt.title('Gender Distribution')
plt.show()

sns.histplot(df['age'].dropna(), kde=True)
plt.title('Age Distribution')
plt.show()

sns.boxplot(x='pclass', y='age', data=df)
plt.title('Age vs Passenger Class')
plt.show()

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

# 5. Check for trends and anomalies
sns.barplot(x='pclass', y='survived', data=df)
plt.title('Survival Rate by Passenger Class')
plt.show()

# 6. Hypothesis test: Survival rate by gender
survival_by_gender = df.groupby('sex')['survived'].mean()
print("\nSurvival Rate by Gender:")
print(survival_by_gender)

